# See example here: https://github.com/yoheimuta/protolint/blob/master/_example/config/.protolint.yaml
lint:
  rules:
    # Set the default to all linters.
    all_default: true
  
  # Linter rules option.
  rules_option:
    # MAX_LINE_LENGTH rule option.
    max_line_length:
      # Enforces a maximum line length
      max_chars: 80